'use strict';

let Nation = (function() {
	let Nation = {};
	
	Nation.themes = [
		{name:'Barbarism', desc:'with brutal savagery'},
		{name:'Decadence', desc:'of sins and fadings'},
		{name:'Despair', desc:'with good things unlooked for'},
		{name:'Exhaustion', desc:'with strength spent and lost'},
		{name:'Ignorance', desc:'of terrors and the unknown'},
		{name:'Oppression', desc:'with rule a crrushing weight'},
		{name:'Poverty', desc:'where even the rich are poor'},
		{name:'Precarity', desc:'with all goods made fleeting'},
		{name:'Stratification', desc:'where classes do not touch'},
		{name:'Violence', desc:'where life is something cheap'},
		{name:'Enlightenment', desc:'where knowledge is loved'},
		{name:'Expansion', desc:'where things swell greater'},
		{name:'Hope', desc:'that the future should be better'},
		{name:'Justice', desc:'where a reckoning is had'},
		{name:'Legitimacy', desc:'where rulers are by right'},
		{name:'Pageantry', desc:'of splendor and magnificence'},
		{name:'Prosperity', desc:'with wealth easily had'},
		{name:'Renewal', desc:'with things growing brighter'},
		{name:'Triumph', desc:'with victory a fresh memory'},
		{name:'Unity', desc:'where purposes are shared'},
	];
	
	Nation.examples = [
		'Victorian England',
		'Standard Medieval Fantasy Land',
		'Spring and Autumn China',
		'Pre-Columbian North American Tribes',
		'Mali Empire',
		'Unified Dynastic China',
		'Imperial or Republican Rome',
		'Greek City States',
		'Mongolian Steppe Nomads',
		'Modern Day America',
		'Renaissance Italy',
		'Imperial Persia',
		'Early Midieval Europe',
		'Byzantine Empire',
		'Incan Empire',
		'Fantasy Viking Land',
		'Sumerian or Assyrian Empire',
		'Aztec Empire',
		'Post-Islamic Arabia',
		'Polynesian Islanders'
	];
	
	Nation.historyEvents = [
		'battleground',
		'betrayal',
		'brutal oppression',
		'class struggle',
		'consequences',
		'decadence',
		'depravity',
		'desolation',
		'diplomatic coup',
		'economic boom',
		'enemies within',
		'evil wizard',
		'exodus',
		'exquisite art',
		'external war',
		'freakish magic',
		'golden age',
		'good wizard',
		'great awakening',
		'great builders',
		'great infrastructure',
		'hero king',
		'immigrants',
		'inefficient rule',
		'internal war',
		'loss of confindence',
		'magical disaster',
		'magical tech',
		'natural calamity',
		'new horizons',
		'new rulers',
		'noble function',
		'noble strife',
		'plague',
		'poverty',
		'power brokers',
		'praetorian coups',
		'priest king',
		'rare resource',
		'religious fall',
		'religious rise',
		'resource collapse',
		'secesssion',
		'terrain change',
		'total collapse',
		'twist of fate',
		'urbanization',
		'weak throne',
		'xenophillia',
		'xenophobia'
	];
	
	return Nation;
}) ();