let Tags = (function() {
	let Tags = {};
	
	Tags.wilderness = [
		"Abandoned Village",
		"Ancient Guadians",
		"Ancient Monument",
		"Arratu Land",
		"Bandit Lair",
		"Beast Swarm",
		"Blighted Tribe",
		"Broken Infrastructure",
		"Chokepoint",
		"Collapsed Deep",
		"Criminal Meet",
		"Cryptic Art",
		"Cursed Land",
		"Decayed Working",
		"Demihuman Community",
		"Devil Grove",
		"Disused Mine",
		"Healing Terrain",
		"Hermitage",
		"Historical Survival",
		"Isolated Academy",
		"Labyrinthine Tangle",
		"Lost Battlefield",
		"Lost City",
		"Magical Springs",
		"Migration Path",
		"Military Outpost",
		"Monstrous Beast",
		"Motherlode",
		"Nomad Camp",
		"Outsider Enclave",
		"Overgrown Tomb",
		"Perilous Path",
		"Pilgramage Site",
		"Precious Game",
		"Rampant Experiment",
		"Refugee Camp",
		"Remnant Road",
		"Remote Monastary",
		"Ruined Fortification",
		"Savage Hamlet",
		"Sculpted Terrain",
		"Seductive Peril",
		"Taboo Territory",
		"Toxic Ruins",
		"Treacherous Terrain",
		"Twisted Fauna",
		"Uncanny Weather",
		"Working Wreckage",
		"Zealot Colony"
	];
	
	Tags.community = [
		'Ancient Infrastructure',
		'Bad Neighbors',
		'Blood Feud',
		'Brilliant Innovation',
		'Broken Spirits',
		'Corrupt Laws',
		'Criminal Bosses',
		'Cultural Center',
		'Cursed Circumstances',
		'Decadent Locals',
		'Decaying Working',
		'Demihuman Populace',
		'Dueling Lords',
		'Enemy Within',
		'Faded Remnant',
		'Fallen Prosperity',
		'Foreign Enclave',
		'Guild Oligarchy',
		'Heavy Fortification',
		'Hidden Ruler',
		'Hostile Terrain',
		'Incompetent Leaders',
		'Inherited Architecture',
		'Inhuman Cooperation',
		'Lawless Class',
		'Magical Academy',
		'Martial Tradition',
		'Miserable Penury',
		'Mistreated Blighted',
		'Monstrous Tribute',
		'Neglectful Ruler',
		'New Industry',
		'Pilgramage Site',
		'Plagued City',
		'Population Boom',
		'Raider Scourge',
		'Rebel Stronghold',
		'Rigid Castes',
		'Scars of War',
		'Seat of Rule',
		'Secret Treachery',
		'Sinking City',
		'Theocractic Authorities',
		'Toxic Economy',
		'Trade Hub',
		'Unique Product',
		'Upstart Faith',
		'Warring Council',
		'Widespread Prosperity',
		'Xenophobic Locals'
	];
	
	Tags.ruin = [
		'Ancient Archives',
		'Invincible Delusion',
		'Aspiring Conqueror',
		'Lethal Treasure',
		'Automaton Servants',
		'Limited Access',
		'Birthing Cyst',
		'Lingering Curse',
		'Bitter Remnants',
		'Living Dungeon',
		'Civil War',
		'Lost Colony',
		'Cyclical Doom',
		'Magical Wonder',
		'Decrepit Structure',
		'Monster Forge',
		'Desperate Hunger',
		'Outsider Domain',
		'Dire Tombs',
		'Precious Resource',
		'Distant Gate',
		'Raider Lair',
		'Dungeon Heart',
		'Recruiting Drive',
		'Experimental Lab',
		'Religious Zealots',
		'Failed Intrusion',
		'Rigid Hierarchy',
		'Fallen Sanctuary',
		'Royal Refuge',
		'False Front',
		'Sacrificial Bargain',
		'Feral Magic',
		'Sealed Evil',
		'Flooded Halls',
		'Secret Alliance',
		'Freshly Looted',
		'Shifting Interior',
		'Friendly Foes',
		'Spatial Flux',
		'Hidden Within',
		'Surfacer Hideout',
		'Hiveminded Natives',
		'Taboo Place',
		'Hospitable Natives',
		'Things Below',
		'Hostile Environment',
		'Useless Treasure',
		'Infectious Miasma',
		'Wizard\'s Lair'
	];
	
	Tags.inhabitantTypesWilderness = [
		'Alpha predator of the area',
		'Intelligent monstrous beings',
		'Swarms or packs of dangerous beasts',
		'Violently reclusive local natives',
		'Remnant of a destroyed state',
		'Survivors of a displaced ethnic group',
		'Demihumans who prefer isolation',
		'Bestially savage tribals, perhaps inhuman',
		'Expedition from a surrounding nation',
		'Prospectors or resource-hunters',
		'Spirit or elemental related to the wilderness',
		'Sorcerers, cultists, or other solitude-lovers'
	];
	
	Tags.inhabitantTypesArratu = [
		'Animate and lethal plant life',
		'Remnants of the Outsiders who made it',
		'Adventurers daring the perilous terrain',
		'Human natives trapped here for generations',
		'Humanoids adapted to life there',
		'Blighted raiders semi-native to the place',
		'Automatons built to serve or fight the arratu',
		'Outsider ruler still controlling a site within',
		'Undead shades of swallowed cities or lands',
		'Vicious alien fauna',
		'Human cultist-servitors of the Outsiders',
		'Explorers searching for a route through'
	];
	
	Tags.ruinRolls = [
		{label:'How Old is the Ruin?', options:[
			'Very fresh; ruined within living memory',
			'Generations old at the least',
			'Part of a known prior nation or polity',
			'Belonging to the unfathomable past'
		]},
		{label:'What Basic Kind of Ruin is it?', options:[
			'A city or other major settlement',
			'Temple, monastery, or pilgrimage site',
			'A vast ancient civil infrastructure center',
			'Artistic monument or aesthetic structure',
			'Grand private residence or manor',
			'Fortress or great stronghold',
			'Mine or tunnel system',
			'Wizard’s tower or occult stronghold',
			'Border outpost, watchtower, or garrison',
			'Village or small rural community',
			'Nonhuman settlement or edifice',
			'Tomb, necropolis, ossuary, or graveyard'
		]},
		{label:'What do the locals think of it?', options:[
			'It’s traditionally taboo ground to them',
			'It plays a role in some important ritual',
			'It and its perils are hated and feared',
			'It’s considered someone’s private property',
			'It’s a lure to the greedy and reckless',
			'They totally misunderstand what it really is'
		]},
		{label:'How did it become ruined?', options:[
			'It was invaded and destroyed by its enemies',
			'Strife from within tore it apart',
			'Some natural calamity despoiled it',
			'A Working’s failure or magical disaster struck',
			'It was abandoned when it became useless',
			'A plague or curse made it uninhabitable',
			'Some dire monster or great foe smashed it',
			'Its inhabitants died out or simply left it'
		]},
		{label:'Who has used the ruin before?', options:[
			'Rebels against the local ruler',
			'Bandits or other criminal outcasts',
			'Fanatical religious zealots',
			'A failed pretender to the local rulership',
			'Refugees and survivors from a calamity',
			'A wizard of dubious habits or goals',
			'A black market trader to bandits or worse',
			'Overly optimistic settlers trying to reclaim it',
			'A hapless garrison of local troops',
			'Monstrous entities lying in wait',
			'Savage beasts of a dangerous kind',
			'Adventurers trying to make it a base',
			'Social outcasts looking for a haven',
			'Demihumans trying to avoid human places',
			'Smugglers seeking a good stash spot',
			'Nominal owners trying to lay claim to it',
			'Heirs or survivors of the original inhabitants',
			'An invading warband based here for a while',
			'Intelligent monsters suited to the environment',
			'Restless undead and embittered shades'
		]},
		{label:'Why hasn\'t it been plundered bare yet?', options:[
			'The environment around it is very dangerous',
			'It’s cursed, plagued, or has some miasma',
			'The locals kill or drive off looters',
			'The true entrance to it is unknown',
			'It’s physically very difficult to access',
			'It’s believed inhabited by fearsome things',
			'Everyone thinks it’s already been looted',
			'It’s confused with a nearby site that is looted',
			'It’s claimed by a powerful local authority',
			'The prizes it offers aren’t conventional riches'
		]}
	];
	
	Tags.villageRolls = [
		{label:'Rational for the Village\'s Existance', options:[
			'Once a garrison outpost of a nation',
			'A mine or quarry, perhaps now exhausted',
			'A spot where refugees of a calamity settled',
			'Holy ground or a temple to a particular faith',
			'A plant or animal grows very well here',
			'It is a safe waypost on a trade route',
			'Refuge for a despised minority or group',
			'A bandit camp that went legitimate',
			'A self-ruled home for demihuman residents',
			'It is a dafe base for salvage or ruin plundering',
			'Decayed remnant of an ancient city',
			'It grew up around a lordly manor or estate'
		]},
		{label:'Who Runs It?', options:[
			'A hereditary Headman',
			'A reeve picked by a lord',
			'a temple representative',
			'a council of elders',
			'a cruel and feared bully',
			'a popularly-chosen chief',
			'a dreaded sorceror',
			'a pragmatic warlord',
			'The richest native here',
			'a traditional squire',
			'a patriarch or matriarch',
			'an organization\'s envoy'
		]},
		{label:'Significant Local', options:[
			'The village harlot',
			'The worst local bully',
			'a gifted young peasant',
			'A half-savage shepherd',
			'a charismatic priest',
			'a major landowner',
			'a youth who wants out',
			'venerable old farmer',
			'criminal in rural hiding',
			'native hedge-mage',
			'a noble\'s local reeve',
			'important artisan'
		]},
		{label:'Current Problem', options:[
			'Vital food stores have been lost or stolen',
			'Two families are in a long-running feud',
			'A new religion is making trouble with the old',
			'The lord’s reeve has been given unreasonable quotas',
			'An upstart newcomer is disrupting the native hierarchy',
			'A socially marginal family is suspected of crimes',
			'A dangerous beast or foe is lurking near the place',
			'A local bully and his friends are causing trouble',
			'The crops or herds are in very poor condition',
			'An ambiguous land dispute is getting bloody',
			'A curse or magical woe is vexing the people',
			'Noble quarrels have caused collateral damage'
		]},
		{label:'Local Likely to Interact with Adventurers', options:[
			'An ambitious local who wants to get to the city',
			'Social outcast who can’t ask any local for help',
			'Gentry who wants no local gossip about their need',
			'Ex-city dweller eager for contact with the worldly',
			'Comparatively rich villager with a need',
			'Starry-eyed young local swooning for adventurers',
			'Village priest in need of outside help',
			'Reeve who can’t reasonably call on natives for a job',
			'Village leader who wants expendable help',
			'Burly local militiaman who watches new faces here',
			'Shifty native who wants some clueless accomplices',
			'Clan patriarch who doesn’t want to use their own kin'
		]},
		{label:'Interesting Things the Place can offer Heroes', options:[
			'An unusually large amount of saved coinage',
			'Valuable local specialty product',
			'Heirloom magic item passed down to the leader',
			'A magical service unique to a local tradition',
			'A map or secret leading to a Deep or plunder site',
			'A temple with potent healing magics available',
			'A secret treasure acquired generations ago',
			'Large amounts of produce or local products',
			'Ownership of an abandoned farm or structure',
			'Contacts with rural bandits or criminal rings',
			'Favors from the lord who’s very fond of the village',
			'Young locals willing to take service with the party'
		]}
	];
	
	Tags.tribeRolls = [
		{label:'Why Are They Staying Here?', options:[
			'It’s an unusually well-fortified safe place',
			'A charismatic leader bound them together',
			'The hunting or resources are very good here',
			'They were driven here by a dire enemy',
			'Seers or shamans said it was ordained',
			'The leadership wants to find something here',
			'Their herds or prey have led them here',
			'They’ve been trapped here by the situation',
			'They’re paralyzed by internal dissent',
			'They’ve been paid or induced to be here',
			'Tradition requires they come here',
			'Here they can do the most damage to a foe'
		]},
		{label:'Who Runs It?', options:[
			'Bestially savage tyrant',
			'Wizened elder',
			'magically-gifted cheif',
			'Holy man or woman',
			'Hereditary cheiftain',
			'Outsider or alien lord',
			'Brutal but cunning cheif',
			'Foreigner turned ruler',
			'Council or elders',
			'No ruler past clan heads',
			'Envoy of a patron power',
			'Most charismatic native'
		]},
		{label:'Significant Local', options:[
			'Best hunter in the tribe',
			'Wise man or woman',
			'Seer or shaman',
			'Tribal artisan',
			'Skilled scout',
			'Trader with outsiders',
			'Adopted member',
			'Tribal slave',
			'Feared troublemaker',
			'Tribe\'s most eligible youth',
			'Barely-tolerated wretch',
			'Cunning tribal advisor'
		]},
		{label:'Current Pressing Problem', options:[
			'The leader is becoming weak or acting foolishly',
			'A settled group is hunting them as mortal foes',
			'A curse has been laid on them for some collective sin',
			'They killed someone who had very powerful allies',
			'They’re impoverished and can’t reach new resources',
			'A fearsome beast hunts them in the wilds',
			'Their gods are sending dire but obscure omens to them',
			'The tribe threatens to split under some feud or quarrel',
			'Some are seeking a redder, more powerful god to serve',
			'A patron power is using them as expendable fodder',
			'A sickness is raging through the tribe',
			'A rival group has taken over their hunting grounds'
		]},
		{label:'Local Likely to Interact with Adventurers', options:[
			'Raid-taken slave looking for a way back home',
			'Leader with a natural suspicion about outsiders',
			'Low-status native trying to acquire outside support',
			'Tribal sage who likes news of the outside world',
			'Curious young tribal interested in strangers',
			'Near-outcast who wants a hand with some revenge',
			'Envoy of another group suspicious of other influences',
			'Tribal notable who suspects the PCs as potential rivals',
			'Tribal trader who wants access to outside goods',
			'Youth determined to show how tribal ways are best',
			'Eligible native looking for new blood in a mate',
			'Reformer or innovator whose kindred won’t listen'
		]},
		{label:'Interesting Things the Place can offer heroes', options:[
			'Guidance and safe passage through their territory',
			'Knowledge of a hidden place of wealth',
			'Exotic and valuable tribal goods',
			'Plunder taken from a foreigner they’ve killed',
			'Inherited relic or treasure they’ve kept',
			'Secret for accessing an otherwise sealed place',
			'Loot won in battle against another group',
			'They’ll raid the party’s enemies for a share of the loot',
			'A magical elixir or substance they know how to make',
			'Tribal membership and a place of respect',
			'Slaves they’ve taken in raids or tribal wars',
			'Some young tribals willing to go with the party'
		]}
	];
	
	return Tags;
}) ();